### ISSUE TITLE
Zori v1 — Roadmap

### ISSUE THREAD

**Issue by thibaudcolas** [FlipFlopWeekly/zori#3]
## Must have
- [ ] Logo (Laurent)
- [ ] Harmoniser la home (Laurent)
- [ ] Coder (Laurent, Seb, Thib)
- [ ] Déployer sur un environnement de prod (Thib)
## Priority list
- [ ] Définir une liste de fonctionnalités attendues et les prioriser (Laurent, Seb, Thib)
